//Direwolf Names
::Const.Strings.PH_DirewolfNames <- [
"Fenrir",
"Grimfang",
"Ravencall",
"Dreadhowl",
"Ironjaw",
"Whitefang",
"Ivoryfang",
"Snowpelt",
"Bloodbane",
"Voidmaw",
"White Devil",
];

//Ghost (banshee really)
::Const.Strings.PH_GhostNames <- [
"Myst",
"Arie",
"Muse",
"Shaydo",
"Spec ",
"Daimon",
"Waythe",
"Torne",
"Curce",
"Ethern ",
"Guardi",
"Flowe",
"Auris",
"Guya",
"Aethe ",
"Auriel",
"Ellis",
"Gloria",
"Sentina ",
];

::Const.Strings.PH_GhostTitles <- [
"The Moaning Banshee",
"The Grievous Angel",
"The Heartrending Fiancee",
"The Woeful Widow",
"The Craven Dame",
"The Fading Bride",
"The Skinny Soul",
"The Humming Daughter",
"The Forsaken Mother",
"The Dread Matriarch",
"The Drifting Nurse ",
"The Thin Servant",
"The Running Wraith",
"The Drained Angel",
"The Sorrowing Gal",
"The Whimpering Fiancee",
"The Silver Wraith",
"The Sniveling Soul",
"The Fading Specter",
"The Tortured Spirit",
"The Flustered Dame",
];

//Ancient Priests
::Const.Strings.PH_SkeletonPriestNames <- [
"Caeso Turullius Synistor",
"Spurius Julius Rullus",
"Octavianus Petilius Iustus",
"Aulus Sextius Fadus",
"Decius Titiedius Linus",
"Aulus Caesennius Traianus",
"Galerius Calventius Ursacius",
"Cnaeus Caerellius Bonifatius",
"Titus Mucius Antius",
"Titus Licinius Quietus",
"Lars Bruccius Rectus",
"Mamercus Gellius Banquerius",
"Gnaeus Pompeius Facilis",
"Lucius Caecius Valentinian",
"Quintus Spurius Carantus",
"Faustus Petilius Bibaculus",
"Nonus Vesuvius Nerva",
"Opiter Amatius Surus",
"Caelus Canuleius Tertulus",
"Amulius Helvetius Tertulus",
];

//Spiders
::Const.Strings.PH_SpiderNames <- [
    "Senqul",
"Zolnurhes",
"Lhortirhith",
"Klanquh",
"Klochishreth",
"Henchal",
"Szassal",
"Qheezhuvhel",
"Soth'ezher",
"Lith\'ashi ",
"Zhozsor",
"Rhet'ieve",
"In\'qer",
"Lezukka",
"Qecheq'riq",
"Lekkaq",
"Laqerteh",
"Lakicheer",
"Chicaq",
"Centi ",
"Aq\'zacer",
"Ozsad",
"Okzot",
"Qiarrovis",
"Ikki",
"Qiq\'zad",
"Reecud",
"Zrairantiq",
"Nezrieq",
"Checheciq",
];

//Witch/Mage titles
::Const.Strings.PH_WitchTitles <- [
"the Hag",
"the Witch-Queen",
"the Coven-Mistress",
"the Dark",
"the Beldame",
"the Carlin",
"the Seeress",
"the Thaumaturge",
];

//Ghouls
::Const.Strings.PH_GhoulNames <- [
"Joz",
"Khox",
"Chud",
"Zunkuq",
"Chusqoc",
"Rablud",
"Boz",
"Khak",
"Kox",
"Zuznux",
"Kixzix",
"Utgag",
];

::Const.Strings.PH_GhoulTitles <- [
"Mirechewer",
"Fangsplitter",
"Hairdripper",
"Siltflayer",
"Sludgefang",
"Blightcrown",
"Cursestrider",
"Grumblebrace",
];

::Const.Strings.PH_SnakeNames <- [
"Zseeke",
"Ikhe",
"Xacserzuz",
"Shirzosko",
"Ikshatshi",
"Jonja",
"Ayacshetsaiss",
"Nathinkhu",
"Syaishiezs",
"Vrathamvrabha",
];

::Const.Strings.PH_GiantNames <- [
"ZIXOM",
"KREOG",
"ALOS",
"GRAZGIR",
"SRUFUR",
"ZLOGRYM",
"KRAZKAOS",
"ITOR",
"TEKRUS",
"DRAFUR",
"RACOS",
"AIVAR",
"EGGAN",
"JISOG",
"MEGAM",
"NEDMALOG",
"SIGAN",
"WIBOG",
"BOTHOR",
"KLAKDHOR",
];

::Const.Strings.PH_TreeNames <- [
"Larchroar",
"Densesprout",
"Ashstump",
"Alderhusk",
"Burnoak",
"Canelaurel",
"Canella",
"Cecos",
"Cecropia",
"Delonin",
"Delonix",
"Ulmal",
"Ulmus",
"Talisarian",
"Talipariti",
];

::Const.Strings.PH_LindwurmNames <- [
"Epcoatl",
"Iztaayocoatl",
"Miccatecoatl",
"Tapachcoatl",
"Huehxolocoatl",
"Ilhuicaacoatl",
"Izhuacoatl",
"Tlacamayecoatl",
"Ticicoatl",
"Colcoatl",
"Tlahuilcoatl",
"Miquilizcoatl",
"Miztoncoatl",
"Yecacoatl",
"Xocoatl",
"Xihuicoatl",
"Ichcacoatl",
"Tlacatecolocoatl",
"Nacacehcoatl",
"Papalocoatl",
];